<?php

namespace Database\Seeders;

use App\Models\Email;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EmailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create 20 email records with static data (no Faker dependency)
        $emails = [
            // 5 new emails
            [
                'message_id' => '<email-001@example.com>',
                'subject' => 'Project Alpha Final Documents Review',
                'from_address' => 'john.doe@company.com',
                'to_addresses' => json_encode(['team@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subDays(1),
                'status' => 'new',
                'has_attachments' => true,
                'eml_path' => 'emails/2024/01/15/email-001.eml',
                'size_bytes' => 2048576,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],
            [
                'message_id' => '<email-002@example.com>',
                'subject' => 'Contract Amendment Request Documentation',
                'from_address' => 'sarah.miller@legal.com',
                'to_addresses' => json_encode(['legal@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subHours(6),
                'status' => 'new',
                'has_attachments' => false,
                'eml_path' => null,
                'size_bytes' => 15360,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],
            [
                'message_id' => '<email-003@example.com>',
                'subject' => 'Q4 Financial Report Analysis',
                'from_address' => 'mike.johnson@finance.com',
                'to_addresses' => json_encode(['finance@docmanager.com', 'management@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subHours(12),
                'status' => 'new',
                'has_attachments' => true,
                'eml_path' => 'emails/2024/01/15/email-003.eml',
                'size_bytes' => 5120000,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],
            [
                'message_id' => '<email-004@example.com>',
                'subject' => 'Legal Compliance Update Requirements',
                'from_address' => 'anna.lee@compliance.com',
                'to_addresses' => json_encode(['compliance@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subDays(2),
                'status' => 'new',
                'has_attachments' => false,
                'eml_path' => null,
                'size_bytes' => 8192,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],
            [
                'message_id' => '<email-005@example.com>',
                'subject' => 'Meeting Notes Action Items',
                'from_address' => 'david.smith@project.com',
                'to_addresses' => json_encode(['project@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subHours(3),
                'status' => 'new',
                'has_attachments' => true,
                'eml_path' => 'emails/2024/01/15/email-005.eml',
                'size_bytes' => 1024000,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],

            // 8 processed emails
            [
                'message_id' => '<email-006@example.com>',
                'subject' => 'Invoice Processing Documentation',
                'from_address' => 'billing@vendor.com',
                'to_addresses' => json_encode(['accounts@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subDays(5),
                'status' => 'processed',
                'has_attachments' => true,
                'eml_path' => 'emails/2024/01/10/email-006.eml',
                'size_bytes' => 3072000,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],
            [
                'message_id' => '<email-007@example.com>',
                'subject' => 'Security Audit Report Findings',
                'from_address' => 'security@audit.com',
                'to_addresses' => json_encode(['security@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subDays(7),
                'status' => 'processed',
                'has_attachments' => false,
                'eml_path' => null,
                'size_bytes' => 25600,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],
            [
                'message_id' => '<email-008@example.com>',
                'subject' => 'Software License Renewal Notice',
                'from_address' => 'licenses@software.com',
                'to_addresses' => json_encode(['it@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subDays(10),
                'status' => 'processed',
                'has_attachments' => true,
                'eml_path' => 'emails/2024/01/05/email-008.eml',
                'size_bytes' => 1536000,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],
            [
                'message_id' => '<email-009@example.com>',
                'subject' => 'Employee Handbook Updates',
                'from_address' => 'hr@company.com',
                'to_addresses' => json_encode(['hr@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subDays(12),
                'status' => 'processed',
                'has_attachments' => true,
                'eml_path' => 'emails/2024/01/03/email-009.eml',
                'size_bytes' => 4096000,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],
            [
                'message_id' => '<email-010@example.com>',
                'subject' => 'Vendor Contract Negotiations',
                'from_address' => 'procurement@vendor.com',
                'to_addresses' => json_encode(['procurement@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subDays(15),
                'status' => 'processed',
                'has_attachments' => false,
                'eml_path' => null,
                'size_bytes' => 12288,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],
            [
                'message_id' => '<email-011@example.com>',
                'subject' => 'Training Materials Distribution',
                'from_address' => 'training@education.com',
                'to_addresses' => json_encode(['training@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subDays(18),
                'status' => 'processed',
                'has_attachments' => true,
                'eml_path' => 'emails/2023/12/28/email-011.eml',
                'size_bytes' => 8192000,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],
            [
                'message_id' => '<email-012@example.com>',
                'subject' => 'Insurance Policy Renewal',
                'from_address' => 'insurance@provider.com',
                'to_addresses' => json_encode(['insurance@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subDays(20),
                'status' => 'processed',
                'has_attachments' => true,
                'eml_path' => 'emails/2023/12/26/email-012.eml',
                'size_bytes' => 2048000,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],
            [
                'message_id' => '<email-013@example.com>',
                'subject' => 'Equipment Maintenance Schedule',
                'from_address' => 'maintenance@service.com',
                'to_addresses' => json_encode(['facilities@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subDays(22),
                'status' => 'processed',
                'has_attachments' => false,
                'eml_path' => null,
                'size_bytes' => 18432,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],

            // 4 archived emails
            [
                'message_id' => '<email-014@example.com>',
                'subject' => 'Old Project Documentation Archive',
                'from_address' => 'archive@oldproject.com',
                'to_addresses' => json_encode(['archive@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subDays(30),
                'status' => 'archived',
                'has_attachments' => true,
                'eml_path' => 'emails/2023/12/16/email-014.eml',
                'size_bytes' => 10240000,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],
            [
                'message_id' => '<email-015@example.com>',
                'subject' => 'Completed Task Documentation',
                'from_address' => 'completed@task.com',
                'to_addresses' => json_encode(['completed@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subDays(35),
                'status' => 'archived',
                'has_attachments' => false,
                'eml_path' => null,
                'size_bytes' => 6144,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],
            [
                'message_id' => '<email-016@example.com>',
                'subject' => 'Historical Data Backup',
                'from_address' => 'backup@historical.com',
                'to_addresses' => json_encode(['backup@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subDays(40),
                'status' => 'archived',
                'has_attachments' => true,
                'eml_path' => 'emails/2023/12/06/email-016.eml',
                'size_bytes' => 5120000,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],
            [
                'message_id' => '<email-017@example.com>',
                'subject' => 'Legacy System Migration',
                'from_address' => 'legacy@system.com',
                'to_addresses' => json_encode(['legacy@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subDays(45),
                'status' => 'archived',
                'has_attachments' => true,
                'eml_path' => 'emails/2023/12/01/email-017.eml',
                'size_bytes' => 3072000,
                'locked_by_user_id' => null,
                'locked_at' => null,
            ],

            // 2 locked emails
            [
                'message_id' => '<email-018@example.com>',
                'subject' => 'Urgent Security Incident Report',
                'from_address' => 'security@incident.com',
                'to_addresses' => json_encode(['security@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subHours(2),
                'status' => 'new',
                'has_attachments' => true,
                'eml_path' => 'emails/2024/01/15/email-018.eml',
                'size_bytes' => 4096000,
                'locked_by_user_id' => 1,
                'locked_at' => now()->subMinutes(30),
            ],
            [
                'message_id' => '<email-019@example.com>',
                'subject' => 'Critical System Update Required',
                'from_address' => 'system@update.com',
                'to_addresses' => json_encode(['system@docmanager.com']),
                'cc_addresses' => null,
                'bcc_addresses' => null,
                'sent_at' => now()->subHours(4),
                'status' => 'processed',
                'has_attachments' => false,
                'eml_path' => null,
                'size_bytes' => 20480,
                'locked_by_user_id' => 2,
                'locked_at' => now()->subMinutes(15),
            ],

            // 1 email with attachments and locked
            [
                'message_id' => '<email-020@example.com>',
                'subject' => 'Complex Legal Document Review',
                'from_address' => 'legal@complex.com',
                'to_addresses' => json_encode(['legal@docmanager.com']),
                'cc_addresses' => json_encode(['review@docmanager.com']),
                'bcc_addresses' => null,
                'sent_at' => now()->subHours(1),
                'status' => 'new',
                'has_attachments' => true,
                'eml_path' => 'emails/2024/01/15/email-020.eml',
                'size_bytes' => 15360000,
                'locked_by_user_id' => 3,
                'locked_at' => now()->subMinutes(5),
            ],
        ];

        // Insert all emails
        foreach ($emails as $emailData) {
            Email::create($emailData);
        }

        $this->command->info('Created 20 email records with varied states (no Faker dependency).');
    }
}
